# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.com/platform/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip
      - python -m pip install uv
    install:
      - uv sync --active --frozen --no-default-groups --group docs

sphinx:
  configuration: docs/conf.py
